# Book settings
title: Programming for Data Science at URI Fall 2020
author: Professor Sarah M Brown
logo: logo.png

parse:
  myst_extended_syntax: true

html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  home_page_in_navbar       : true
  # extra_navbar              : Download complete <a href="">PDF</a> # Will be displayed underneath the



latex:
  latex_documents:
    targetname: book.tex
